### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by vihangatheturtle** [BobHasNoSoul/jellyfin-featured#3]
The CSS doesnt seem to be loading, at http://localhost:8096/web/avatars/slideshow.html, it is showing the CSS as text in the header <style> tag

![image](https://github.com/BobHasNoSoul/jellyfin-featured/assets/43118457/2a5e6e52-8f25-45c4-a38c-7d398f7940d9)
![image](https://github.com/BobHasNoSoul/jellyfin-featured/assets/43118457/06fc99c6-a0b6-4555-b1ab-385fcb90b143)

**Comment by vihangatheturtle** [comment]
I think I have found a fix:

```css
@media (max-width: 768px) {
.item-description {
    position: absolute;
    bottom: 1px !important;
    left: 1px !important;
    color: white;
    font-size: 14px !important;
    max-width: 100vw !important;
    padding: 2px !important;
    background: linear-gradient(to right, rgba(0, 0, 0, 0>
    /* background: linear-gradient(to right, rgba(0, 0, 0>
    border-radius: 5px!important;
    z-index: 999999;
}
}
```

change to:

```css
@media (max-width: 768px) {
.item-description {
    position: absolute;
    bottom: 1px !important;
    left: 1px !important;
    color: white;
    font-size: 14px !important;
    max-width: 100vw !important;
    padding: 2px !important;
    background: linear-gradient(to right, rgba(0, 0, 0, 0>));
    /* background: linear-gradient(to right, rgba(0, 0, 0> */
    border-radius: 5px!important;
    z-index: 999999;
}
}
```

Dont have time to make a PR atm, sorry
